### ISSUE TITLE
Suggestion: Guest-user support

### ISSUE THREAD

**Issue by Aaron2550** [Xenthys/ShareXen#14]
Add support to upload files without a username/password that will get automatically deleted after a set time/never

**Comment by Xenthys** [comment]
Automated deletion is unsupported: this is a stateless API without any kind of database, tracking upload times and running a task in the background to delete files would break that premise. Please use a fully-featured project like [Lutim](https://framagit.org/fiat-tux/hat-softwares/lutim) which allows anonymous and temporary uploads if you need that, with client-side encryption pretty much like ZeroBin/PrivateBin as well.

Regarding the unauthenticated access, it would be a liability more than anything else, but you can already create a public token that you can share with everyone, it can be anything you want of course. Disabling the authentication entirely is also possible by editing the code a bit of course, but it will never be a readily available option due to the aforementioned security and liability reasons!
